# Key to learning documentation---> documentation----> documentation

In [1]:
import torch
import numpy

In [2]:
device='cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

### 1. Create a random tensor with shape ``(7,7).``


In [3]:
tensor_2=torch.rand(7,7)
print(f'Random tensor with size (7,7) is:\n {tensor_2}')

Random tensor with size (7,7) is:
 tensor([[0.3574, 0.8110, 0.3711, 0.2652, 0.1258, 0.8701, 0.2852],
        [0.0180, 0.2853, 0.7374, 0.1956, 0.7324, 0.2614, 0.8434],
        [0.8456, 0.4172, 0.1117, 0.0740, 0.1114, 0.2883, 0.6441],
        [0.4742, 0.5400, 0.2809, 0.4939, 0.1478, 0.4801, 0.8842],
        [0.2643, 0.3429, 0.5419, 0.6340, 0.0265, 0.3093, 0.4696],
        [0.1316, 0.0420, 0.9673, 0.9405, 0.3357, 0.0610, 0.8745],
        [0.8039, 0.5572, 0.7114, 0.2045, 0.5239, 0.6516, 0.1886]])


### 2. Perform a matrix multiplicatin on the tensor from 2 with another random tensor with shape (1,7).

In [4]:
tensor_3=torch.rand(1,7).T
print(f'Matrix multiplicaiton of\n {tensor_2}\nand \n{ tensor_3} \nis: {tensor_2@tensor_3}\n')

Matrix multiplicaiton of
 tensor([[0.3574, 0.8110, 0.3711, 0.2652, 0.1258, 0.8701, 0.2852],
        [0.0180, 0.2853, 0.7374, 0.1956, 0.7324, 0.2614, 0.8434],
        [0.8456, 0.4172, 0.1117, 0.0740, 0.1114, 0.2883, 0.6441],
        [0.4742, 0.5400, 0.2809, 0.4939, 0.1478, 0.4801, 0.8842],
        [0.2643, 0.3429, 0.5419, 0.6340, 0.0265, 0.3093, 0.4696],
        [0.1316, 0.0420, 0.9673, 0.9405, 0.3357, 0.0610, 0.8745],
        [0.8039, 0.5572, 0.7114, 0.2045, 0.5239, 0.6516, 0.1886]])
and 
tensor([[0.6233],
        [0.7635],
        [0.5428],
        [0.0691],
        [0.5649],
        [0.9786],
        [0.1147]]) 
is: tensor([[2.0170],
        [1.4091],
        [1.3303],
        [1.5492],
        [1.1360],
        [1.0537],
        [2.2821]])



### 3. Set random seed to 0 and do qn no 1 and 2 again.

In [5]:
SEED=0
torch.manual_seed(SEED)
Stensor_2=torch.rand(7,7)
torch.manual_seed(SEED)
Stensor_3=torch.rand(1,7).T
print(f'Matrix multiplicaiton of\n {Stensor_2}\nand \n{ Stensor_3} \nis: {Stensor_2@Stensor_3}\n')



Matrix multiplicaiton of
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
and 
tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]]) 
is: tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])



### 4. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [6]:
torch.cuda.manual_seed(1234)

### 5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed)

In [7]:
torch.manual_seed(1234)
Gtensor_1=torch.rand(2,3).to('cuda')

torch.manual_seed(1234)
Gtensor_2=torch.rand(2,3).to('cuda')


### 6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [8]:
output=Gtensor_1 @ Gtensor_2.T
print(f'Matrix mulitplication of \n{Gtensor_1}\n and\n {Gtensor_2}\n is: {Gtensor_1 @ Gtensor_2.T}')

Matrix mulitplication of 
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
 and
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
 is: tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')


### 7. Find the maximum and minimum values of the output of above.

In [9]:
print('Approach_1\nMaximum value is:',output.max())
print('Approach_2\nMaximum value is:',torch.max(output))

print('Approach_1\nMinimum value is:',output.min())
print('Approach_2\nMinimum value is:',torch.min(output))

Approach_1
Maximum value is: tensor(0.6287, device='cuda:0')
Approach_2
Maximum value is: tensor(0.6287, device='cuda:0')
Approach_1
Minimum value is: tensor(0.2161, device='cuda:0')
Approach_2
Minimum value is: tensor(0.2161, device='cuda:0')


### 8. Find the maximun and minimum index values for 6.

In [10]:
print('Approach_1\nMaximum index is:',output.argmax())
print('Approach_2\nMaximum index is:',torch.argmax(output))

print('Approach_1\nMinimum index is:',output.argmin())
print('Approach_2\nMinimum index is:',torch.argmin(output))

Approach_1
Maximum index is: tensor(3, device='cuda:0')
Approach_2
Maximum index is: tensor(3, device='cuda:0')
Approach_1
Minimum index is: tensor(1, device='cuda:0')
Approach_2
Minimum index is: tensor(1, device='cuda:0')


### 9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [11]:
torch.manual_seed(7)
tensor_9=torch.rand(1,1,1,10)


In [12]:
tensor9_squeezed=torch.squeeze(tensor_9)
tensor9_squeezed.shape

torch.Size([10])

In [13]:
print(tensor_9, tensor_9.shape)
print(tensor9_squeezed, tensor9_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
