<a href="https://www.kaggle.com/code/sachinkoirla/00-pytorch-fundamentals?scriptVersionId=199136831" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# What is PyTorch?
PyTorch is a Python-based scientific computing package serving two broad purposes:
- A replacement for NumPy to use the power of GPUs
- A deep learning research platform that provides maximum flexibility and speed

### Who uses PyTorch?
- Facebook
- Twitter
- Salesforce
- Tesla
- Uber


In [2]:
import torch
import numpy as np
import pandas as pd

In [3]:
#set device to cuda if available which is one of the functionalities of pytorch
device=('cuda' if torch.cuda.is_available() else 'cpu')
device

'cuda'

# 1. Introduction to Tensor
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array. <br> Tensors are the basic building blocks of PyTorch.
For more information, visit the official [PyTorch documentation](https://pytorch.org/docs/stable/tensors.html).

## 1.1 Creating Tensor
we can create a tensor in PyTorch using the `torch.tensor()` method. <br>
First we will create a scalar which is a 0-dimensional tensor.

In [5]:
#scalar
scalar=torch.tensor(42)
print(scalar)
print(scalar.shape)
print(scalar.ndim)
print(scalar.dtype)

tensor(42)
torch.Size([])
0
torch.int64


<p >That means although scalar is a single number, it's of type torch.Tensor. <br>
We checked the dimensions of a tensor using the ndim attribute.<br>
What if we wanted to retrieve the number from the tensor? i.e instead of tensor(42), we just want 42. <br>
To do we can use the item() method. </p>

In [6]:
scalar.item()

42

In [ ]:
#vector
#vector is 1D tensor , it is set of scalar values
vector=torch.tensor([1,2])
print(vector)
print(vector.shape)
print(vector.ndim)

tensor([1, 2])
torch.Size([2])
1


Above vector contains two numbers but only has a single dimension. How? <br> 
Trick: You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ```([)``` and you only need to count one side.


In [10]:
#MATRIX
#matrix is 2D tensor , it is set of vectors 

MATRIX=torch.tensor([[1,2],
                     [3,4]
                    ])
print(MATRIX)
print(MATRIX.shape)
print(MATRIX.ndim)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
2


In [19]:
#TENSOR
#tensor is 3D tensor , it is set of matrix
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       ])


tensor=torch.tensor([[[1,2],
                      [5,6],
                      [9,1]]])
print(TENSOR)
print(tensor)
print(TENSOR.shape, tensor.shape)
print(TENSOR.ndim, tensor.ndim)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
tensor([[[1, 2],
         [5, 6],
         [9, 1]]])
torch.Size([1, 3, 3]) torch.Size([1, 3, 2])
3 3


In [32]:
#acessing the elements of the tensor
print(f'{TENSOR[0][0]}') # accessing the first matrix of the tensor
print(f'{TENSOR[0][0][0]}') # accessing the first element of the first matrix of the tensor
print(f'{TENSOR[0][0][0:2]}') # accessing the first two elements of the first matrix of the tensor
print(" ")
print(f'{TENSOR[0][1]}') # accessing the second matrix of the tensor
print(f'{TENSOR[0][1][0]}') # accessing the first element of the second matrix of the tensor


tensor([1, 2, 3])
1
tensor([1, 2])
 
tensor([3, 6, 9])
3


![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

## 1.2 Random Tensor
While building machine learning models we rarely create tensor by hand.<br>
Instead, we initialize tensors with random values and then update them during training.<br>
* What we do is:<br>
    ```Start with random values --> learn from data --> update values --> repeat.```

We can create random tensors using the `torch.rand()` method. <br>

In [8]:
#creating random tensor
random_tensor=torch.rand(10,3)

In [9]:
random_image_size_tensor=torch.rand(size=(3,224,224)) # or torch.rand(3,224,224)

In [10]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

## 1.3 Creating random tensor of zeroes and ones

Sometimes we want to create a tensor of zeroes or ones. This generally happens when we want to initialize the weights of a neural network. <br>

In [11]:

zeroes=torch.zeros(size=(2,2))
zeroes

tensor([[0., 0.],
        [0., 0.]])

In [12]:
ones=torch.ones(size=(2,2))
ones

tensor([[1., 1.],
        [1., 1.]])

## 1.4 Creating a range of tensors and tensor  like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use ```torch.arange(start, end, step)``` to do so.

Where:

* ```start``` = start of range (e.g. 0)
* ```end``` = end of range (e.g. 10)
* ```step``` = how many steps in between each value (e.g. 1)

In [34]:
#Tensor range
one_to_ten=torch.arange(0,10,2) # start, end , step 

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use ```torch.zeros_like(input)``` or ```torch.ones_like(input)``` which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [35]:
#tensor like
print(torch.ones_like(one_to_ten))
print(torch.zeros_like(one_to_ten))
print(torch.ones_like(torch.tensor([1,1,1,1])))
print(torch.ones_like(torch.arange(1,10)))

tensor([1, 1, 1, 1, 1])
tensor([0, 0, 0, 0, 0])
tensor([1, 1, 1, 1])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])


## 1.5 Tensor datatypes
There are different datatypes in PyTorch. Some of the most commonly used ones are:
- torch.float: 32-bit floating-point
- torch.double: 64-bit double-precision floating-point
- torch.int: 32-bit integer (signed)
- torch.long: 64-bit integer (signed)

for more information, visit the official [PyTorch Tensor datatypes documentation](https://pytorch.org/docs/stable/tensors.html).

Datatypes are important in PyTorch because they determine what kind of data a tensor can hold. This is also one of the most common errors you might encounter when working with PyTorch tensors. so, it's important to keep track of the datatypes of tensors.



In [36]:
float32_tensor=torch.tensor([3,1,2],
                            dtype=torch.float32,
                            device=None,
                            requires_grad=False) # This will be covered in later sections
print(float32_tensor.dtype)

torch.float32


In [37]:
#changing tesor type
float16_tensor=float32_tensor.type(torch.float16)
float16_tensor.dtype

torch.float16

In [39]:
(float16_tensor*float32_tensor).dtype

torch.float32

# 2. Getting information from tensors

1. Tensors not right datatype - `tensor.dtype`
2. Tensor  not right shape    - `tensor.shape`
3. Tensor  not right device   - `tensor.device`

## Manipulating Tensors

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [18]:
tensor=torch.tensor([9,1,2])
vectorr=torch.ones(size=(1,2,2))

In [19]:
#addition
print(vectorr+10) #adds 10 to each element
print(tensor+20)

tensor([[[11., 11.],
         [11., 11.]]])
tensor([29, 21, 22])


In [20]:
#subtraction 
print(vectorr-10)
print(tensor-20)

tensor([[[-9., -9.],
         [-9., -9.]]])
tensor([-11, -19, -18])


In [21]:
#multiplicaiton (element-wise)
print(tensor*2)
print(vectorr*2)

tensor([18,  2,  4])
tensor([[[2., 2.],
         [2., 2.]]])


In [22]:
#torch inbuild function for manipulations 

print(torch.add(tensor,2))
print(torch.sub(tensor,2))
print(torch.mul(tensor,2))
print(torch.div(tensor,2))

tensor([11,  3,  4])
tensor([ 7, -1,  0])
tensor([18,  2,  4])
tensor([4.5000, 0.5000, 1.0000])


In [23]:
# Matrix mulitiplication
%time
a=torch.tensor([1,2,3])
print(torch.matmul(a,a))


CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 7.15 µs
tensor(14)


In [24]:
a@a #same as matrix multiplication

tensor(14)

In [25]:
%time
value=0
for i in range(len(a)):
    value+=a[i]*a[i]
value

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 6.44 µs


tensor(14)

## Finding the min, max,mean,sum

In [26]:
x=torch.arange(1,10)


In [27]:
#find the min
torch.min(x),x.min()

(tensor(1), tensor(1))

In [28]:
#find the max
torch.max(x),x.max()

(tensor(9), tensor(9))

In [29]:
#find the mean
x=x.type(torch.float32) #try commenthing this line and check it
torch.mean(x)

tensor(5.)

In [30]:
#find the sum
torch.sum(x),x.sum()

(tensor(45.), tensor(45.))

## Finding the Positional min and max

In [31]:
xx=torch.rand([4])
xx

tensor([0.4365, 0.0082, 0.6548, 0.1940])

In [32]:
print(xx.argmin()) # throws the index where minimum value lies
print(xx.argmax()) # throws the index where maximum value lies

tensor(1)
tensor(2)


## Reshaping, Stacking, Squeezing , Unsqueezeing, Permute, View

In [33]:
y=torch.arange(0.0,9.0)
y,y.shape

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([9]))

In [34]:
#reshape
y_reshaped=y.reshape(1,9)  # one row , 9 columns
y_reshaped_again=y.reshape(9,1) # 9 rows , one column


In [35]:
#view
y_view=y.view(3,3)  #same as reshape but here the memory is shared i.e if we change y_view, y will also change

y_view[-1]= -9    # this will also change last element of y

In [36]:
#stack
#for dim=0 whole matrix will stack on top
#or dim=1 new dimension created between row and column,
#for dim=2 every element will make a pair
y_stacked= torch.stack([y_view,-y_view],dim=1)
print(y_view.ndim)
y_stacked

2


tensor([[[ 0.,  1.,  2.],
         [-0., -1., -2.]],

        [[ 3.,  4.,  5.],
         [-3., -4., -5.]],

        [[-9., -9., -9.],
         [ 9.,  9.,  9.]]])

In [37]:
#squeeze --> removes single dimension

print(f'orginal tensor: {y_reshaped}')
print(f'orginal tensor shape:{y_reshaped.shape}')

print(f'\nsqueezed tensor: {y_reshaped.squeeze()}')
print(f'squeezed tensor shape:{y_reshaped.squeeze().shape}')


orginal tensor: tensor([[ 0.,  1.,  2.,  3.,  4.,  5., -9., -9., -9.]])
orginal tensor shape:torch.Size([1, 9])

squeezed tensor: tensor([ 0.,  1.,  2.,  3.,  4.,  5., -9., -9., -9.])
squeezed tensor shape:torch.Size([9])


In [38]:
#unsqueeze
print(f'orignal tensor:{y}')
print(f'orginal tensor shape:{y.shape}')
print(f'\nunsqueezed tensor:{y.unsqueeze(dim=0)}')
print(f'unsqueezed tensor shape:{y.unsqueeze(dim=0).shape}')
print(f'\nunsqueezed tensor:{y.unsqueeze(dim=1)}')
print(f'unsqueezed tensor shape:{y.unsqueeze(dim=1).shape}')

orignal tensor:tensor([ 0.,  1.,  2.,  3.,  4.,  5., -9., -9., -9.])
orginal tensor shape:torch.Size([9])

unsqueezed tensor:tensor([[ 0.,  1.,  2.,  3.,  4.,  5., -9., -9., -9.]])
unsqueezed tensor shape:torch.Size([1, 9])

unsqueezed tensor:tensor([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [-9.],
        [-9.],
        [-9.]])
unsqueezed tensor shape:torch.Size([9, 1])


In [39]:
#permute --> rearranges the dimension its like view
img=torch.rand(size=(224,224,3))
print(img.shape)
new_img=img.permute(2,0,1) #change in new_img will change img

torch.Size([224, 224, 3])


## Indexing

In [40]:
num=torch.arange(1,10).reshape(1,3,3)
num,num.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [41]:
num[0][1][2] #you know this its like normal indexing

tensor(6)

In [42]:
num[:,:,1]

tensor([[2, 5, 8]])

In [43]:
num[:,0,0]

tensor([1])

In [44]:
num[0,0,:]

tensor([1, 2, 3])

In [45]:
num[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors and numpy

In [46]:
n=np.arange(1.0,8.0)
t=torch.from_numpy(n) #numpy array are in float64 by default

print(t)

nn=torch.ones(7)
nump=nn.numpy()

print(nn,nn.dtype)

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1., 1., 1.]) torch.float32


## Reproducibility

In [47]:
random_seed=42
torch.manual_seed(random_seed) #use this line before creating any random torch
rand_a=torch.rand(3,4)

torch.manual_seed(random_seed) #use this line before creating any random torch
rand_b=torch.rand(3,4)

In [48]:
print(rand_a==rand_b)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Creating tensor on GPU

In [49]:
tens=torch.rand([5,5],device='cpu')
tens,tens.device

(tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854],
         [0.5739, 0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695, 0.3588],
         [0.1994, 0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090, 0.5779]]),
 device(type='cpu'))

In [50]:
#changing from cpu to gpu
tens.to(device).device #make sure cuda is enabled first

device(type='cpu')

### Moving tensor back to CPU


In [51]:
# if the tensor in in gpu then we can't transform it into numpy
#so first comvert into cpu and then to numpy cant do directly
tens.numpy() #this won't work if tens was in gpu
tens.cpu().numpy() #this is correct approach

array([[0.86940444, 0.5677153 , 0.74109405, 0.4294045 , 0.8854429 ],
       [0.57390445, 0.26658005, 0.62744915, 0.26963168, 0.44136357],
       [0.29692084, 0.8316855 , 0.10531491, 0.26949483, 0.35881263],
       [0.19936377, 0.54719156, 0.00616044, 0.95155454, 0.07526588],
       [0.8860137 , 0.5832096 , 0.33764774, 0.808975  , 0.5779254 ]],
      dtype=float32)